<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211123135553 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE importacion_cubano');
        $this->addSql('DROP TABLE reporte');
        $this->addSql('DROP TABLE tipo_cliente');
        $this->addSql('DROP TABLE tipo_pago');
        $this->addSql('DROP TABLE usuario');
        $this->addSql('ALTER TABLE buque CHANGE puerto_salida_id puerto_salida_id INT DEFAULT NULL, CHANGE buque_activo buque_activo TINYINT(1) DEFAULT NULL, CHANGE fecha_desactivacion fecha_desactivacion DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE categoria_cliente CHANGE fecha fecha DATETIME DEFAULT NULL, CHANGE fecha_insercion fecha_insercion DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE cliente CHANGE pais_id pais_id INT DEFAULT NULL, CHANGE categoria_cliente_id categoria_cliente_id INT DEFAULT NULL, CHANGE fecha fecha DATETIME DEFAULT NULL, CHANGE fecha_insercion fecha_insercion DATE DEFAULT NULL, CHANGE fecha_vencimiento_certifico_inmigracion fecha_vencimiento_certifico_inmigracion DATE DEFAULT NULL, CHANGE cliente_activo cliente_activo TINYINT(1) DEFAULT NULL, CHANGE fecha_desactivacion fecha_desactivacion DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE contenedor CHANGE buque_id buque_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE contrato CHANGE tipo_contrato_id tipo_contrato_id INT DEFAULT NULL, CHANGE fecha_vencimiento fecha_vencimiento DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE desglose_manifiesto CHANGE contenedor_id contenedor_id INT DEFAULT NULL, CHANGE numero_multa numero_multa INT DEFAULT NULL');
        $this->addSql('ALTER TABLE expediente CHANGE naviera_id naviera_id INT DEFAULT NULL, CHANGE contenedor_id contenedor_id INT DEFAULT NULL, CHANGE pais_id pais_id INT DEFAULT NULL, CHANGE provincia_id provincia_id INT DEFAULT NULL, CHANGE desglose_manifiesto_id desglose_manifiesto_id INT DEFAULT NULL, CHANGE importacion_cubano_id importacion_cubano_id INT DEFAULT NULL, CHANGE numero_expediente numero_expediente VARCHAR(100) DEFAULT NULL, CHANGE telefono_fijo telefono_fijo VARCHAR(50) DEFAULT NULL, CHANGE telefono_movil telefono_movil VARCHAR(50) DEFAULT NULL, CHANGE numero_manifiesto numero_manifiesto VARCHAR(100) DEFAULT NULL, CHANGE certificoInmigracion certificoInmigracion VARCHAR(100) DEFAULT NULL, CHANGE franquiciaDiplomatica franquiciaDiplomatica VARCHAR(10) DEFAULT NULL, CHANGE cartaOriginal cartaOriginal VARCHAR(100) DEFAULT NULL, CHANGE desglose desglose VARCHAR(100) DEFAULT NULL, CHANGE manifiesto manifiesto VARCHAR(100) DEFAULT NULL, CHANGE fecha_entregado_deposito fecha_entregado_deposito DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE exportacion CHANGE solicitud_servicio_id solicitud_servicio_id INT DEFAULT NULL, CHANGE condicion_compra_id condicion_compra_id INT DEFAULT NULL, CHANGE puerto_origen_id puerto_origen_id INT DEFAULT NULL, CHANGE puerto_destino_id puerto_destino_id INT DEFAULT NULL, CHANGE contenedor_id contenedor_id INT DEFAULT NULL, CHANGE contrato_id contrato_id INT DEFAULT NULL, CHANGE tipo_moneda_id tipo_moneda_id INT DEFAULT NULL, CHANGE via_transportacion_id via_transportacion_id INT DEFAULT NULL, CHANGE numero_exportacion numero_exportacion VARCHAR(100) DEFAULT NULL, CHANGE costo_origen costo_origen DOUBLE PRECISION DEFAULT NULL, CHANGE flete flete DOUBLE PRECISION DEFAULT NULL, CHANGE destino destino DOUBLE PRECISION DEFAULT NULL, CHANGE recargo recargo DOUBLE PRECISION DEFAULT NULL, CHANGE rx rx DOUBLE PRECISION DEFAULT NULL, CHANGE presupuesto presupuesto DOUBLE PRECISION DEFAULT NULL, CHANGE fecha_desactivacion fecha_desactivacion DATE DEFAULT NULL, CHANGE exportacion_activa exportacion_activa TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE importa_cubano CHANGE provincia_id provincia_id INT DEFAULT NULL, CHANGE pais_procedencia_id pais_procedencia_id INT DEFAULT NULL, CHANGE transitario_id transitario_id INT DEFAULT NULL, CHANGE naviera_id naviera_id INT DEFAULT NULL, CHANGE desglose_manifiesto_id desglose_manifiesto_id INT DEFAULT NULL, CHANGE contenedor_id contenedor_id INT DEFAULT NULL, CHANGE solicitud_servicio_id solicitud_servicio_id INT DEFAULT NULL, CHANGE estado_servicio_id estado_servicio_id INT DEFAULT NULL, CHANGE fecha_entrega_aduana fecha_entrega_aduana DATE DEFAULT NULL, CHANGE fecha_autorizo_embarque fecha_autorizo_embarque DATE DEFAULT NULL, CHANGE numero_importacion_cubano numero_importacion_cubano VARCHAR(100) DEFAULT NULL, CHANGE expediente_ok expediente_ok TINYINT(1) DEFAULT NULL, CHANGE importacion_cubana_activa importacion_cubana_activa TINYINT(1) DEFAULT NULL, CHANGE fecha_desactivacion fecha_desactivacion DATE DEFAULT NULL, CHANGE fecha_arribo fecha_arribo DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE importacion CHANGE condicion_compra_id condicion_compra_id INT DEFAULT NULL, CHANGE contenedor_id contenedor_id INT DEFAULT NULL, CHANGE contrato_id contrato_id INT DEFAULT NULL, CHANGE puerto_destino_id puerto_destino_id INT DEFAULT NULL, CHANGE puerto_origen_id puerto_origen_id INT DEFAULT NULL, CHANGE estado_servicio_id estado_servicio_id INT DEFAULT NULL, CHANGE solicitud_servicio_id solicitud_servicio_id INT DEFAULT NULL, CHANGE tipo_moneda_id tipo_moneda_id INT DEFAULT NULL, CHANGE via_transportacion_id via_transportacion_id INT DEFAULT NULL, CHANGE numero_importacion numero_importacion VARCHAR(100) DEFAULT NULL, CHANGE presupuesto presupuesto DOUBLE PRECISION DEFAULT NULL, CHANGE costo_origen costo_origen DOUBLE PRECISION DEFAULT NULL, CHANGE flete flete DOUBLE PRECISION DEFAULT NULL, CHANGE destino destino DOUBLE PRECISION DEFAULT NULL, CHANGE recargo recargo DOUBLE PRECISION DEFAULT NULL, CHANGE rx rx DOUBLE PRECISION DEFAULT NULL, CHANGE desglose_manifiesto desglose_manifiesto TINYINT(1) DEFAULT NULL, CHANGE importacion_activa importacion_activa TINYINT(1) DEFAULT NULL, CHANGE fecha_desactivacion fecha_desactivacion DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE programacion CHANGE cliente_id cliente_id INT DEFAULT NULL, CHANGE tipo_contenedor_id tipo_contenedor_id INT DEFAULT NULL, CHANGE transitario_id transitario_id INT DEFAULT NULL, CHANGE naviera_id naviera_id INT DEFAULT NULL, CHANGE contenedor_id contenedor_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE rectificacion_desglose_manifiesto CHANGE contenedor_id contenedor_id INT DEFAULT NULL, CHANGE naviera_id naviera_id INT DEFAULT NULL, CHANGE numero_multa numero_multa INT DEFAULT NULL');
        $this->addSql('ALTER TABLE rol ADD descripcion VARCHAR(255) NOT NULL, DROP nombreLegible, CHANGE nombre nombre VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE solicitud_servicio CHANGE tipo_servicio_id tipo_servicio_id INT DEFAULT NULL, CHANGE cliente_id cliente_id INT DEFAULT NULL, CHANGE via_recepcion_id via_recepcion_id INT DEFAULT NULL, CHANGE solicitud_activa solicitud_activa TINYINT(1) DEFAULT NULL, CHANGE fecha_desactivacion fecha_desactivacion DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE user CHANGE roles roles JSON NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE importacion_cubano (id INT AUTO_INCREMENT NOT NULL, provincia_id INT DEFAULT NULL, pais_procedencia_id INT DEFAULT NULL, transitario_id INT DEFAULT NULL, naviera_id INT DEFAULT NULL, contenedor_id INT DEFAULT NULL, solicitud_servicio_id INT DEFAULT NULL, estado_servicio_id INT DEFAULT NULL, desglose_manifiesto_id INT DEFAULT NULL, fecha_entrega_aduana DATE DEFAULT \'NULL\', expediente_ok TINYINT(1) DEFAULT \'NULL\', fecha_arribo DATE DEFAULT \'NULL\', fecha_autorizo_embarque DATE DEFAULT \'NULL\', fecha DATETIME NOT NULL, fecha_insercion DATE NOT NULL, numero_importacion_cubano VARCHAR(100) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, importacion_cubana_activa TINYINT(1) DEFAULT \'NULL\', fecha_desactivacion DATE DEFAULT \'NULL\', INDEX IDX_241A9303896D82D1 (transitario_id), INDEX IDX_241A930369806DFD (solicitud_servicio_id), INDEX IDX_241A93034E7121AF (provincia_id), INDEX IDX_241A9303D21CF971 (naviera_id), INDEX IDX_241A93034BC64AB7 (estado_servicio_id), INDEX IDX_241A9303429FFEC2 (pais_procedencia_id), INDEX IDX_241A9303C1A15772 (contenedor_id), INDEX IDX_241A930336DDC72C (desglose_manifiesto_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE reporte (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tipo_cliente (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, fecha DATETIME DEFAULT \'NULL\', fechaInsercion DATE DEFAULT \'NULL\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tipo_pago (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE usuario (id INT AUTO_INCREMENT NOT NULL, rol_id INT DEFAULT NULL, nombreUsuario VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, nombre VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, primerApellido VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, segundoApellido VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, contrasenna VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, usuarioactivo TINYINT(1) NOT NULL, fechadesactivacion DATE NOT NULL, INDEX IDX_2265B05D4BAB96C (rol_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE importacion_cubano ADD CONSTRAINT FK_241A93034E7121AF FOREIGN KEY (provincia_id) REFERENCES provincia (id)');
        $this->addSql('ALTER TABLE importacion_cubano ADD CONSTRAINT FK_241A9303896D82D1 FOREIGN KEY (transitario_id) REFERENCES transitario (id)');
        $this->addSql('ALTER TABLE importacion_cubano ADD CONSTRAINT FK_241A9303D21CF971 FOREIGN KEY (naviera_id) REFERENCES naviera (id)');
        $this->addSql('ALTER TABLE importacion_cubano ADD CONSTRAINT FK_241A930336DDC72C FOREIGN KEY (desglose_manifiesto_id) REFERENCES desglose_manifiesto (id)');
        $this->addSql('ALTER TABLE importacion_cubano ADD CONSTRAINT FK_241A93034BC64AB7 FOREIGN KEY (estado_servicio_id) REFERENCES estado_servicio (id)');
        $this->addSql('ALTER TABLE importacion_cubano ADD CONSTRAINT FK_241A930369806DFD FOREIGN KEY (solicitud_servicio_id) REFERENCES solicitud_servicio (id)');
        $this->addSql('ALTER TABLE importacion_cubano ADD CONSTRAINT FK_241A9303C1A15772 FOREIGN KEY (contenedor_id) REFERENCES contenedor (id)');
        $this->addSql('ALTER TABLE importacion_cubano ADD CONSTRAINT FK_241A9303429FFEC2 FOREIGN KEY (pais_procedencia_id) REFERENCES pais (id)');
        $this->addSql('ALTER TABLE usuario ADD CONSTRAINT FK_2265B05D4BAB96C FOREIGN KEY (rol_id) REFERENCES rol (id)');
        $this->addSql('ALTER TABLE buque CHANGE puerto_salida_id puerto_salida_id INT DEFAULT NULL, CHANGE buque_activo buque_activo TINYINT(1) DEFAULT \'NULL\', CHANGE fecha_desactivacion fecha_desactivacion DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE categoria_cliente CHANGE fecha fecha DATETIME DEFAULT \'NULL\', CHANGE fecha_insercion fecha_insercion DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cliente CHANGE pais_id pais_id INT DEFAULT NULL, CHANGE categoria_cliente_id categoria_cliente_id INT DEFAULT NULL, CHANGE fecha_vencimiento_certifico_inmigracion fecha_vencimiento_certifico_inmigracion DATE DEFAULT \'NULL\', CHANGE fecha fecha DATETIME DEFAULT \'NULL\', CHANGE fecha_insercion fecha_insercion DATE DEFAULT \'NULL\', CHANGE cliente_activo cliente_activo TINYINT(1) DEFAULT \'NULL\', CHANGE fecha_desactivacion fecha_desactivacion DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE contenedor CHANGE buque_id buque_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE contrato CHANGE tipo_contrato_id tipo_contrato_id INT DEFAULT NULL, CHANGE fecha_vencimiento fecha_vencimiento DATE NOT NULL');
        $this->addSql('ALTER TABLE desglose_manifiesto CHANGE contenedor_id contenedor_id INT DEFAULT NULL, CHANGE numero_multa numero_multa INT DEFAULT NULL');
        $this->addSql('ALTER TABLE expediente CHANGE naviera_id naviera_id INT DEFAULT NULL, CHANGE contenedor_id contenedor_id INT DEFAULT NULL, CHANGE pais_id pais_id INT DEFAULT NULL, CHANGE provincia_id provincia_id INT DEFAULT NULL, CHANGE desglose_manifiesto_id desglose_manifiesto_id INT DEFAULT NULL, CHANGE importacion_cubano_id importacion_cubano_id INT DEFAULT NULL, CHANGE numero_expediente numero_expediente VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE numero_manifiesto numero_manifiesto VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE telefono_fijo telefono_fijo VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE telefono_movil telefono_movil VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE certificoInmigracion certificoInmigracion VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE franquiciaDiplomatica franquiciaDiplomatica VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE cartaOriginal cartaOriginal VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE desglose desglose VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE manifiesto manifiesto VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE fecha_entregado_deposito fecha_entregado_deposito DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE exportacion CHANGE solicitud_servicio_id solicitud_servicio_id INT DEFAULT NULL, CHANGE condicion_compra_id condicion_compra_id INT DEFAULT NULL, CHANGE puerto_origen_id puerto_origen_id INT DEFAULT NULL, CHANGE puerto_destino_id puerto_destino_id INT DEFAULT NULL, CHANGE contenedor_id contenedor_id INT DEFAULT NULL, CHANGE contrato_id contrato_id INT DEFAULT NULL, CHANGE tipo_moneda_id tipo_moneda_id INT DEFAULT NULL, CHANGE via_transportacion_id via_transportacion_id INT DEFAULT NULL, CHANGE numero_exportacion numero_exportacion VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE costo_origen costo_origen DOUBLE PRECISION DEFAULT \'NULL\', CHANGE flete flete DOUBLE PRECISION DEFAULT \'NULL\', CHANGE destino destino DOUBLE PRECISION DEFAULT \'NULL\', CHANGE recargo recargo DOUBLE PRECISION DEFAULT \'NULL\', CHANGE rx rx DOUBLE PRECISION DEFAULT \'NULL\', CHANGE presupuesto presupuesto DOUBLE PRECISION DEFAULT \'NULL\', CHANGE exportacion_activa exportacion_activa TINYINT(1) DEFAULT \'NULL\', CHANGE fecha_desactivacion fecha_desactivacion DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE importa_cubano CHANGE provincia_id provincia_id INT DEFAULT NULL, CHANGE pais_procedencia_id pais_procedencia_id INT DEFAULT NULL, CHANGE transitario_id transitario_id INT DEFAULT NULL, CHANGE naviera_id naviera_id INT DEFAULT NULL, CHANGE desglose_manifiesto_id desglose_manifiesto_id INT DEFAULT NULL, CHANGE contenedor_id contenedor_id INT DEFAULT NULL, CHANGE solicitud_servicio_id solicitud_servicio_id INT DEFAULT NULL, CHANGE estado_servicio_id estado_servicio_id INT DEFAULT NULL, CHANGE fecha_entrega_aduana fecha_entrega_aduana DATE DEFAULT \'NULL\', CHANGE expediente_ok expediente_ok TINYINT(1) DEFAULT \'NULL\', CHANGE fecha_arribo fecha_arribo DATE DEFAULT \'NULL\', CHANGE fecha_autorizo_embarque fecha_autorizo_embarque DATE DEFAULT \'NULL\', CHANGE numero_importacion_cubano numero_importacion_cubano VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE importacion_cubana_activa importacion_cubana_activa TINYINT(1) DEFAULT \'NULL\', CHANGE fecha_desactivacion fecha_desactivacion DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE importacion CHANGE condicion_compra_id condicion_compra_id INT DEFAULT NULL, CHANGE contenedor_id contenedor_id INT DEFAULT NULL, CHANGE contrato_id contrato_id INT DEFAULT NULL, CHANGE puerto_destino_id puerto_destino_id INT DEFAULT NULL, CHANGE puerto_origen_id puerto_origen_id INT DEFAULT NULL, CHANGE estado_servicio_id estado_servicio_id INT DEFAULT NULL, CHANGE solicitud_servicio_id solicitud_servicio_id INT DEFAULT NULL, CHANGE via_transportacion_id via_transportacion_id INT DEFAULT NULL, CHANGE tipo_moneda_id tipo_moneda_id INT DEFAULT NULL, CHANGE numero_importacion numero_importacion VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE presupuesto presupuesto DOUBLE PRECISION DEFAULT \'NULL\', CHANGE costo_origen costo_origen DOUBLE PRECISION DEFAULT \'NULL\', CHANGE flete flete DOUBLE PRECISION DEFAULT \'NULL\', CHANGE destino destino DOUBLE PRECISION DEFAULT \'NULL\', CHANGE recargo recargo DOUBLE PRECISION DEFAULT \'NULL\', CHANGE rx rx DOUBLE PRECISION DEFAULT \'NULL\', CHANGE desglose_manifiesto desglose_manifiesto TINYINT(1) DEFAULT \'NULL\', CHANGE importacion_activa importacion_activa TINYINT(1) DEFAULT \'NULL\', CHANGE fecha_desactivacion fecha_desactivacion DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE programacion CHANGE cliente_id cliente_id INT DEFAULT NULL, CHANGE tipo_contenedor_id tipo_contenedor_id INT DEFAULT NULL, CHANGE transitario_id transitario_id INT DEFAULT NULL, CHANGE naviera_id naviera_id INT DEFAULT NULL, CHANGE contenedor_id contenedor_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE rectificacion_desglose_manifiesto CHANGE contenedor_id contenedor_id INT DEFAULT NULL, CHANGE naviera_id naviera_id INT DEFAULT NULL, CHANGE numero_multa numero_multa INT DEFAULT NULL');
        $this->addSql('ALTER TABLE rol ADD nombreLegible VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, DROP descripcion, CHANGE nombre nombre VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`');
        $this->addSql('ALTER TABLE solicitud_servicio CHANGE tipo_servicio_id tipo_servicio_id INT DEFAULT NULL, CHANGE cliente_id cliente_id INT DEFAULT NULL, CHANGE via_recepcion_id via_recepcion_id INT DEFAULT NULL, CHANGE solicitud_activa solicitud_activa TINYINT(1) DEFAULT \'NULL\', CHANGE fecha_desactivacion fecha_desactivacion DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE user CHANGE roles roles LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`');
    }
}
